-- ============================================================================
-- MIGRATION: offline sync for the desktop client
--
-- Run this ONCE in the Supabase SQL Editor BEFORE deploying the build that
-- adds offline sync - GMS.Web included. That build maps two new columns on
-- every table (sync_id, sync_version) and fails on any table without them.
-- Everything here is idempotent, so re-running it is harmless.
--
-- What it does:
--   * sync_id on every table: a uuid that names a row across the server and
--     every desktop copy. Existing rows are each given their own.
--   * sync_version on every table: stamped by a trigger on each insert and
--     update from one shared sequence, so a desktop can ask for "everything
--     changed since version N".
--   * sync_tombstones: one row per deleted row, written by a trigger, so a
--     desktop learns about deletions too.
--
-- Why it is safe on live data: both columns are added with defaults, nothing
-- existing is changed or removed, and GMS.Web writes exactly as before - the
-- triggers fill the new columns in for it.
--
-- db/supabase/schema.sql carries the same statements at the end, so a
-- database built from nothing has them too. Running either is enough.
-- ============================================================================

begin;

create sequence if not exists gms_sync_version_seq;

create table if not exists sync_tombstones (
    id bigint generated by default as identity primary key,
    table_name text not null,
    row_id integer not null,
    sync_id uuid not null,
    -- NULL for global tables (roles, permissions), which every desktop receives.
    organization_id integer,
    sync_version bigint not null default nextval('gms_sync_version_seq'),
    deleted_at_utc timestamp with time zone not null default now()
);
create index if not exists ix_sync_tombstones_org_version on sync_tombstones (organization_id, sync_version);

-- Not for the Supabase data API. The application connects as the table owner,
-- which row level security does not restrict.
alter table sync_tombstones enable row level security;

create or replace function gms_stamp_sync_version() returns trigger
language plpgsql as $$
begin
    new.sync_version := nextval('gms_sync_version_seq');
    return new;
end
$$;

create or replace function gms_record_tombstone() returns trigger
language plpgsql as $$
declare
    org integer;
begin
    if tg_table_name = 'organizations' then
        org := old.id;
    elsif tg_table_name = 'transaction_lines' then
        -- Lines have no organization_id of their own. When the whole transaction is
        -- being deleted the parent may already be gone; NULL then, which a desktop
        -- matches by sync_id, so the tombstone still lands.
        select t.organization_id into org from transactions t where t.id = old.transaction_id;
    else
        org := (to_jsonb(old) ->> 'organization_id')::integer;
    end if;

    insert into sync_tombstones (table_name, row_id, sync_id, organization_id)
    values (tg_table_name, old.id, old.sync_id, org);
    return old;
end
$$;

do $$
declare
    t text;
begin
    foreach t in array array[
        'organizations', 'subscriptions', 'roles', 'permissions', 'users', 'shops',
        'shop_stocks', 'categories', 'products', 'suppliers', 'customers',
        'transactions', 'transaction_lines', 'stock_movements', 'audit_entries',
        'notifications', 'app_settings'
    ] loop
        execute format('alter table %I add column if not exists sync_id uuid not null default gen_random_uuid()', t);
        execute format('alter table %I add column if not exists sync_version bigint not null default 0', t);
        execute format('create unique index if not exists %I on %I (sync_id)', 'ux_' || t || '_sync_id', t);
        execute format('create index if not exists %I on %I (sync_version)', 'ix_' || t || '_sync_version', t);

        execute format('drop trigger if exists gms_sync_version on %I', t);
        execute format('create trigger gms_sync_version before insert or update on %I '
                       'for each row execute function gms_stamp_sync_version()', t);
        execute format('drop trigger if exists gms_sync_tombstone on %I', t);
        execute format('create trigger gms_sync_tombstone after delete on %I '
                       'for each row execute function gms_record_tombstone()', t);
    end loop;
end
$$;

commit;
