-- ============================================================================
-- MIGRATION: offline sync for the desktop client
--
-- Run this ONCE in the Supabase SQL Editor BEFORE deploying the build that
-- adds offline sync - GMS.Web included. That build maps three new columns on
-- every table (sync_id, sync_version, sync_xid) and fails on any table without
-- them. Everything here is idempotent, so re-running it is harmless.
--
-- What it does:
--   * sync_id on every table: a uuid that names a row across the server and
--     every desktop copy. Existing rows are each given their own.
--   * sync_version and sync_xid on every table: stamped by a trigger on each
--     insert and update with a number from one shared sequence and the id of
--     the writing transaction, so a desktop can ask for "everything changed
--     since I last looked" without missing a transaction that committed late.
--   * sync_tombstones: one row per deleted row, written by a trigger, so a
--     desktop learns about deletions too.
--
-- Why it is safe on live data: every column is added with a default, nothing
-- existing is changed or removed, and GMS.Web writes exactly as before - the
-- triggers fill the new columns in for it.
--
-- db/supabase/schema.sql carries the same statements at the end, so a
-- database built from nothing has them too. Running either is enough.
-- ============================================================================

begin;

create sequence if not exists gms_sync_version_seq;

create table if not exists sync_tombstones (
    id bigint generated by default as identity primary key,
    table_name text not null,
    row_id integer not null,
    sync_id uuid not null,
    -- NULL for global tables (roles, permissions), which every desktop receives.
    organization_id integer,
    sync_version bigint not null default nextval('gms_sync_version_seq'),
    -- The deleting transaction; see gms_stamp_sync_version.
    sync_xid bigint not null default (pg_current_xact_id()::text::bigint),
    deleted_at_utc timestamp with time zone not null default now()
);
alter table sync_tombstones add column if not exists sync_xid bigint not null default (pg_current_xact_id()::text::bigint);
create index if not exists ix_sync_tombstones_xid on sync_tombstones (sync_xid, sync_version);

-- Not for the Supabase data API. The application connects as the table owner,
-- which row level security does not restrict.
alter table sync_tombstones enable row level security;

-- sync_version orders changes; sync_xid is the writing transaction, and is what a desktop
-- pages by. A version is taken when the row is written but only becomes visible when its
-- transaction commits, so paging by version alone can step past a row whose transaction
-- is still open - and never come back for it. A desktop instead reads only transactions
-- older than the oldest one still running (pg_snapshot_xmin), all of which are finished.
create or replace function gms_stamp_sync_version() returns trigger
language plpgsql as $$
begin
    new.sync_version := nextval('gms_sync_version_seq');
    new.sync_xid := pg_current_xact_id()::text::bigint;
    return new;
end
$$;

create or replace function gms_record_tombstone() returns trigger
language plpgsql as $$
declare
    org integer;
begin
    if tg_table_name = 'organizations' then
        org := old.id;
    elsif tg_table_name = 'transaction_lines' then
        -- Lines have no organization_id of their own. When the whole transaction is
        -- being deleted the parent may already be gone; NULL then, which a desktop
        -- matches by sync_id, so the tombstone still lands.
        select t.organization_id into org from transactions t where t.id = old.transaction_id;
    else
        org := (to_jsonb(old) ->> 'organization_id')::integer;
    end if;

    insert into sync_tombstones (table_name, row_id, sync_id, organization_id)
    values (tg_table_name, old.id, old.sync_id, org);
    return old;
end
$$;

do $$
declare
    t text;
begin
    foreach t in array array[
        'organizations', 'subscriptions', 'roles', 'permissions', 'users', 'shops',
        'shop_stocks', 'categories', 'products', 'suppliers', 'customers',
        'transactions', 'transaction_lines', 'stock_movements', 'audit_entries',
        'notifications', 'app_settings'
    ] loop
        execute format('alter table %I add column if not exists sync_id uuid not null default gen_random_uuid()', t);
        execute format('alter table %I add column if not exists sync_version bigint not null default 0', t);
        execute format('alter table %I add column if not exists sync_xid bigint not null default 0', t);
        execute format('create unique index if not exists %I on %I (sync_id)', 'ux_' || t || '_sync_id', t);
        execute format('create index if not exists %I on %I (sync_xid, sync_version)', 'ix_' || t || '_sync_xid', t);

        execute format('drop trigger if exists gms_sync_version on %I', t);
        execute format('create trigger gms_sync_version before insert or update on %I '
                       'for each row execute function gms_stamp_sync_version()', t);
        execute format('drop trigger if exists gms_sync_tombstone on %I', t);
        execute format('create trigger gms_sync_tombstone after delete on %I '
                       'for each row execute function gms_record_tombstone()', t);
    end loop;
end
$$;

commit;
