-- ============================================================================
-- MIGRATION: shops
--
-- Run this ONCE in the Supabase SQL Editor before deploying the build that
-- adds shops. Everything in it is idempotent, so re-running it is harmless.
--
-- What it does:
--   * creates the two new tables (shops, shop_stocks)
--   * adds shop_id to users, transactions and stock_movements
--   * adds unit_price to shop_stocks (per-branch selling price)
--   * adds the indexes and uniqueness rules those need
--
-- Why it is safe on live data: every added column is nullable with no default,
-- so existing rows keep NULL. A NULL shop_id means "the central pool", which is
-- exactly what every row written before shops existed actually was - nothing
-- has to be back-filled and no figure changes.
--
-- db/supabase/schema.sql remains the source of truth and already contains all
-- of this; that file builds a database from nothing, this one upgrades a
-- database that already has data in it. Running either is enough.
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. New tables
-- ---------------------------------------------------------------------------
create table if not exists shops (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    name text,
    code text,
    address text,
    phone text,
    is_active boolean NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_shops" PRIMARY KEY (id),
    CONSTRAINT "FK_shops_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

create table if not exists shop_stocks (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    shop_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity_on_hand numeric(18,6) NOT NULL,
    unit_price numeric(18,6),
    CONSTRAINT "PK_shop_stocks" PRIMARY KEY (id),
    CONSTRAINT "FK_shop_stocks_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT "FK_shop_stocks_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT "FK_shop_stocks_shops_shop_id" FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- 2. New columns on tables that already exist
-- ---------------------------------------------------------------------------
alter table users           add column if not exists shop_id integer;
alter table transactions    add column if not exists shop_id integer;
alter table stock_movements add column if not exists shop_id integer;

-- Only reached when shop_stocks already existed from an earlier run of this
-- file; the CREATE TABLE above includes the column for a first run.
alter table shop_stocks     add column if not exists unit_price numeric(18,6);

-- ---------------------------------------------------------------------------
-- 3. Foreign keys for those columns
--
-- ADD CONSTRAINT has no IF NOT EXISTS, so each one is checked by name first.
-- users is RESTRICT: closing or removing a shop must never take its staff's
-- accounts with it. transactions and stock_movements are SET NULL: the history
-- outlives the shop it happened at, and reads as central once the shop is gone.
-- ---------------------------------------------------------------------------
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'FK_users_shops_shop_id') then
        alter table users add constraint "FK_users_shops_shop_id"
            foreign key (shop_id) references shops (id) on delete restrict;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'FK_transactions_shops_shop_id') then
        alter table transactions add constraint "FK_transactions_shops_shop_id"
            foreign key (shop_id) references shops (id) on delete set null;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'FK_stock_movements_shops_shop_id') then
        alter table stock_movements add constraint "FK_stock_movements_shops_shop_id"
            foreign key (shop_id) references shops (id) on delete set null;
    end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4. Indexes
-- ---------------------------------------------------------------------------
create index if not exists "IX_shops_organization_id"        on shops (organization_id);
create index if not exists "IX_shop_stocks_organization_id"  on shop_stocks (organization_id);
create index if not exists "IX_shop_stocks_product_id"       on shop_stocks (product_id);
create index if not exists "IX_shop_stocks_shop_id"          on shop_stocks (shop_id);
create index if not exists "IX_users_shop_id"                on users (shop_id);
create index if not exists "IX_transactions_shop_id"         on transactions (shop_id);
create index if not exists "IX_stock_movements_shop_id"      on stock_movements (shop_id);

-- Shop codes are unique inside an organisation, never globally: two different
-- customers must both be able to have a branch coded "WL".
create unique index if not exists ux_shops_org_code on shops (organization_id, lower(code));

-- One balance row per product per shop. Two rows for the same pair would split a
-- balance in half and make every availability check wrong.
create unique index if not exists ux_shop_stocks_shop_product on shop_stocks (shop_id, product_id);

-- Covering indexes for the shop-filtered ledger and transaction list.
create index if not exists ix_stock_movements_shop_product on stock_movements (shop_id, product_id, moved_at_utc);
create index if not exists ix_transactions_shop_date       on transactions (organization_id, shop_id, transaction_date);

commit;

-- ============================================================================
-- Nothing else is needed. The new permissions (shops.view, shops.manage,
-- shops.allocate) and the Shop Attendant role are rows, not schema, and the
-- application seeds them itself on start-up - idempotently, so existing
-- organisations pick them up on the first run of the new build.
--
-- Sign-in records are written to the existing audit_entries table with
-- action = 4 (Login); the action column is already an integer, so the clickable
-- login trail needs no schema change either.
-- ============================================================================

-- Check it worked:
--   select column_name from information_schema.columns
--    where table_name = 'shop_stocks' order by ordinal_position;
--   -- expect: id, organization_id, shop_id, product_id, quantity_on_hand, unit_price
--
--   select count(*) from shops;        -- 0 on a database that had none
--   select count(*) from shop_stocks;  -- 0
