Imports System.Linq
Imports GMS.Core.Abstractions
Imports GMS.Core.Enums
Imports GMS.Core.Models
Imports GMS.Core.Security

Namespace Services

    ''' <summary>
    ''' Populates the store with the rows the system needs to run (permissions,
    ''' system roles, one administrator, default settings) and, optionally, a small
    ''' set of demo records. Storage-agnostic: it works against the in-memory unit
    ''' of work now and the Entity Framework one later, unchanged.
    ''' </summary>
    Public NotInheritable Class DataSeeder

        Public Const DefaultAdminUserName As String = "admin"
        Public Const DefaultAdminPassword As String = "ChangeMe#2026"
        Public Const DefaultOrganizationCode As String = "default"

        Private ReadOnly _uow As IUnitOfWork
        Private ReadOnly _hasher As IPasswordHasher
        Private ReadOnly _clock As IClock

        Public Sub New(uow As IUnitOfWork, hasher As IPasswordHasher, clock As IClock)
            _uow = uow
            _hasher = hasher
            _clock = clock
        End Sub

        ''' <summary>Idempotent: safe to call on every startup.</summary>
        Public Sub SeedBaseline()
            Dim defaultOrgId = SeedDefaultOrganization()
            SeedBaseline(organizationId:=defaultOrgId)
        End Sub

        ''' <summary>Idempotent: safe to call for a new organization.</summary>
        Public Sub SeedBaseline(organizationId As Integer)
            ' The SaveChanges calls in here are load-bearing, not tidiness: rows seeded in one
            ' step are referenced by foreign key in the next, and against a real database an
            ' entity has no identity value until it is saved. Deferring every insert to a single
            ' SaveChanges at the end writes role_id = 0 into users and trips
            ' FK_users_roles_role_id. The in-memory store hides this because its repository
            ' hands out an Id on Add, so this code path must be exercised against PostgreSQL.
            SeedPermissions()
            _uow.SaveChanges()

            Dim roles = SeedRoles()
            SeedAdminUser(roles.admin, organizationId)
            SeedSettings(organizationId)
            _uow.SaveChanges()
        End Sub

        ''' <summary>
        ''' Ensures the default organization exists. Returns its ID.
        ''' </summary>
        ''' <remarks>
        ''' The ID is assigned by the store, never hard-coded. Inserting an explicit id = 1 into
        ''' a <c>GENERATED BY DEFAULT AS IDENTITY</c> column does not advance the underlying
        ''' sequence, so the *next* organization created — the first real tenant to sign up —
        ''' is handed id 1 again and dies on PK_organizations. Identified by code rather than
        ''' id for the same reason: nothing should assume the default organization is number 1.
        ''' </remarks>
        Private Function SeedDefaultOrganization() As Integer
            Dim orgRepo = _uow.Repository(Of Organization)()
            Dim existing = orgRepo.Query().FirstOrDefault(Function(o) o.Code = DefaultOrganizationCode)
            If existing IsNot Nothing Then Return existing.Id

            Dim org = New Organization With {
                .Name = "Default Organization",
                .Code = DefaultOrganizationCode,
                .Email = "admin@example.com",
                .Plan = "trial",
                .TrialEndsAtUtc = _clock.UtcNow.AddDays(30),
                .IsActive = True,
                .MaxUsers = 10,
                .Features = "{}",
                .CreatedAtUtc = _clock.UtcNow
            }
            orgRepo.Add(org)
            ' Saved before the subscription so the store assigns org.Id for the foreign key.
            _uow.SaveChanges()

            Dim subRepo = _uow.Repository(Of Subscription)()
            subRepo.Add(New Subscription With {
                .OrganizationId = org.Id,
                .Plan = "trial",
                .PlanName = "Trial",
                .PricePerMonth = 0,
                .AutoRenew = False,
                .BillingCycleStartAtUtc = _clock.UtcNow,
                .BillingCycleEndAtUtc = _clock.UtcNow.AddDays(30),
                .PaymentStatus = "active",
                .CreatedAtUtc = _clock.UtcNow
            })

            _uow.SaveChanges()
            Return org.Id
        End Function

        Private Sub SeedPermissions()
            Dim repo = _uow.Repository(Of Permission)()
            Dim existing = repo.Query().Select(Function(p) p.Code).ToHashSet(StringComparer.OrdinalIgnoreCase)
            For Each def In PermissionCodes.Catalog
                If Not existing.Contains(def.Code) Then
                    repo.Add(New Permission With {.Code = def.Code, .Category = def.Category, .Description = def.Description})
                End If
            Next
        End Sub

        Private Function SeedRoles() As (admin As Role, manager As Role, staff As Role)
            Dim roleRepo = _uow.Repository(Of Role)()

            Dim admin = EnsureRole(roleRepo, "Admin", "Full access to every module.")
            Dim manager = EnsureRole(roleRepo, "Manager", "Day-to-day operations and reporting.")
            Dim staff = EnsureRole(roleRepo, "Staff", "Create transactions and view catalogue.")

            ' Materialise the role IDs before anything references them: SetRolePermissions
            ' writes role_id into role_permissions, and SeedAdminUser writes it into users.
            _uow.SaveChanges()

            SetRolePermissions(admin, PermissionCodes.AllCodes())

            SetRolePermissions(manager, {
                PermissionCodes.Products.View, PermissionCodes.Products.Edit,
                PermissionCodes.Categories.View, PermissionCodes.Categories.Edit,
                PermissionCodes.Customers.View, PermissionCodes.Customers.Edit,
                PermissionCodes.Suppliers.View, PermissionCodes.Suppliers.Edit,
                PermissionCodes.Transactions.View, PermissionCodes.Transactions.Create,
                PermissionCodes.Transactions.Confirm, PermissionCodes.Transactions.Cancel,
                PermissionCodes.Inventory.View, PermissionCodes.Inventory.Adjust,
                PermissionCodes.Reports.View, PermissionCodes.Audit.View
            })

            SetRolePermissions(staff, {
                PermissionCodes.Products.View, PermissionCodes.Categories.View,
                PermissionCodes.Customers.View, PermissionCodes.Customers.Edit,
                PermissionCodes.Suppliers.View,
                PermissionCodes.Transactions.View, PermissionCodes.Transactions.Create,
                PermissionCodes.Inventory.View
            })

            Return (admin, manager, staff)
        End Function

        Private Function EnsureRole(repo As IRepository(Of Role), name As String, description As String) As Role
            Dim role = repo.Query().FirstOrDefault(Function(r) r.Name.ToLower() = name.ToLower())
            If role Is Nothing Then
                role = New Role With {.Name = name, .Description = description, .IsSystem = True}
                repo.Add(role)
            End If
            Return role
        End Function

        Private Sub SetRolePermissions(role As Role, codes As IEnumerable(Of String))
            Dim permRepo = _uow.Repository(Of Permission)()
            Dim rpRepo = _uow.Repository(Of RolePermission)()
            Dim wanted = codes.ToHashSet(StringComparer.OrdinalIgnoreCase)
            Dim existing = rpRepo.Query().Where(Function(rp) rp.RoleId = role.Id).Select(Function(rp) rp.PermissionId).ToHashSet()

            For Each perm In permRepo.Query().Where(Function(p) wanted.Contains(p.Code))
                If Not existing.Contains(perm.Id) Then
                    rpRepo.Add(New RolePermission With {.RoleId = role.Id, .PermissionId = perm.Id})
                End If
            Next
        End Sub

        Private Sub SeedAdminUser(adminRole As Role, organizationId As Integer)
            Dim repo = _uow.Repository(Of User)()
            ' Always scoped to the organization being seeded. Checking the name alone would let
            ' the first tenant's "admin" suppress every later tenant's own administrator,
            ' leaving that organization with no way to sign in. Filtered in two steps for the
            ' same EF/VB closure-translation reason described in SeedSettings.
            Dim namesInOrg = repo.Query().
                Where(Function(u) u.OrganizationId = organizationId).
                Select(Function(u) u.UserName).
                ToHashSet(StringComparer.OrdinalIgnoreCase)
            If namesInOrg.Contains(DefaultAdminUserName) Then Return

            repo.Add(New User With {
                .UserName = DefaultAdminUserName,
                .Email = "admin@example.com",
                .FullName = "System Administrator",
                .RoleId = adminRole.Id,
                .OrganizationId = organizationId,
                .IsActive = True,
                .MustChangePassword = True,
                .PasswordHash = _hasher.Hash(DefaultAdminPassword),
                .CreatedAtUtc = _clock.UtcNow
            })
        End Sub

        Private Sub SeedSettings(organizationId As Integer)
            Dim repo = _uow.Repository(Of AppSetting)()
            Dim defaults As New Dictionary(Of String, String) From {
                {SettingKeys.CompanyName, "My Business"},
                {SettingKeys.CurrencyCode, "KES"},
                {SettingKeys.DefaultTaxRatePercent, "0"},
                {SettingKeys.LowStockScanEnabled, "true"},
                {SettingKeys.TimeZone, "Africa/Nairobi"}
            }
            ' Read this organization's existing keys once, then decide in memory. Testing each
            ' key with a separate Any(...) closing over both the loop variable and the method
            ' parameter is what EF fails to translate - it emits the VB closure field name as a
            ' SQL identifier ("syntax error at or near Closure_2_$VB$Local_organizationId").
            ' One round trip instead of five is the happy side effect.
            Dim existingKeys = repo.Query().
                Where(Function(s) s.OrganizationId = organizationId).
                Select(Function(s) s.Key).
                ToHashSet(StringComparer.OrdinalIgnoreCase)

            For Each kv In defaults
                ' Scoped per organization: every tenant gets its own copy of each setting.
                If Not existingKeys.Contains(kv.Key) Then
                    repo.Add(New AppSetting With {
                        .Key = kv.Key,
                        .Value = kv.Value,
                        .OrganizationId = organizationId
                    })
                End If
            Next
        End Sub

        ''' <summary>
        ''' Adds a handful of demo records if the catalogue is empty. Uses the real
        ''' services so stock movements and totals are produced the normal way.
        ''' </summary>
        Public Sub SeedDemo(categories As CategoryService, products As ProductService, transactions As TransactionService,
                            customers As CustomerService, suppliers As SupplierService)
            If _uow.Repository(Of Product)().Query().Any() Then Return

            Dim general = categories.Create("General", "Uncategorised items", Nothing)
            Dim office = categories.Create("Office Supplies", "Stationery and consumables", Nothing)

            Dim supplier = suppliers.Create(New SupplierInput With {.Name = "Acme Wholesale", .Email = "sales@acme.example"})
            Dim customer = customers.Create(New CustomerInput With {.Name = "Walk-in Customer", .Code = "WALKIN"})

            Dim p1 = products.Create(New ProductInput With {
                .Sku = "PEN-BLUE", .Name = "Ballpoint Pen (Blue)", .CategoryId = office.Value.Id,
                .UnitPrice = 1.2D, .CostPrice = 0.4D, .ReorderLevel = 50D})
            Dim p2 = products.Create(New ProductInput With {
                .Sku = "PAD-A4", .Name = "A4 Notepad", .CategoryId = office.Value.Id,
                .UnitPrice = 3.5D, .CostPrice = 1.5D, .ReorderLevel = 20D})
            Dim p3 = products.Create(New ProductInput With {
                .Sku = "BOX-SM", .Name = "Small Storage Box", .CategoryId = general.Value.Id,
                .UnitPrice = 6D, .CostPrice = 3D, .ReorderLevel = 10D})

            ' Opening stock via a confirmed purchase.
            Dim po = transactions.CreateDraft(TransactionType.Purchase, supplier.Value.Id, _clock.UtcNow, "Opening stock")
            transactions.AddLine(po.Value.Id, New TransactionLineInput With {.ProductId = p1.Value.Id, .Quantity = 200D})
            transactions.AddLine(po.Value.Id, New TransactionLineInput With {.ProductId = p2.Value.Id, .Quantity = 40D})
            transactions.AddLine(po.Value.Id, New TransactionLineInput With {.ProductId = p3.Value.Id, .Quantity = 25D})
            transactions.Confirm(po.Value.Id)

            ' One confirmed sale.
            Dim so = transactions.CreateDraft(TransactionType.Sale, customer.Value.Id, _clock.UtcNow, "First sale")
            transactions.AddLine(so.Value.Id, New TransactionLineInput With {.ProductId = p1.Value.Id, .Quantity = 12D})
            transactions.AddLine(so.Value.Id, New TransactionLineInput With {.ProductId = p3.Value.Id, .Quantity = 2D})
            transactions.Confirm(so.Value.Id)
        End Sub
    End Class

End Namespace
