-- ============================================================================
--  General Management System — Supabase / PostgreSQL schema
-- ----------------------------------------------------------------------------
--  Run this in the Supabase SQL Editor (or psql) against your project.
--  Safe to re-run: every object uses IF NOT EXISTS / ON CONFLICT DO NOTHING.
--
--  Table & column names are snake_case so they map cleanly from GMS.Core's
--  PascalCase model via EF Core's snake-case naming convention.
--
--  Datetime columns are timestamptz and the app writes UTC values.
--  Enum columns are stored as integer (values listed next to each column).
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. Identity & access
-- ---------------------------------------------------------------------------

create table if not exists roles (
    id           integer generated by default as identity primary key,
    name         text    not null,
    description  text    not null default '',
    is_system    boolean not null default false
);
create unique index if not exists ux_roles_name_lower on roles (lower(name));

create table if not exists permissions (
    id           integer generated by default as identity primary key,
    code         text not null,
    description  text not null default '',
    category     text not null default ''
);
create unique index if not exists ux_permissions_code on permissions (code);

create table if not exists role_permissions (
    role_id       integer not null references roles (id)       on delete cascade,
    permission_id integer not null references permissions (id) on delete cascade,
    primary key (role_id, permission_id)
);
create index if not exists ix_role_permissions_permission on role_permissions (permission_id);

create table if not exists users (
    id                    integer generated by default as identity primary key,
    user_name             text    not null,
    email                 text    not null default '',
    full_name             text    not null default '',
    password_hash         text    not null,
    role_id               integer not null references roles (id) on delete restrict,
    is_active             boolean not null default true,
    must_change_password  boolean not null default false,
    last_login_utc        timestamptz,
    failed_login_count    integer not null default 0,
    locked_out_until_utc  timestamptz,
    created_at_utc        timestamptz not null default now(),
    created_by_user_id    integer,
    updated_at_utc        timestamptz,
    updated_by_user_id    integer
);
create unique index if not exists ux_users_user_name_lower on users (lower(user_name));
create index if not exists ix_users_role on users (role_id);

-- ---------------------------------------------------------------------------
-- 2. Catalogue & parties
-- ---------------------------------------------------------------------------

create table if not exists categories (
    id                  integer generated by default as identity primary key,
    name                text not null,
    description         text not null default '',
    parent_category_id  integer references categories (id) on delete set null,
    created_at_utc      timestamptz not null default now(),
    created_by_user_id  integer,
    updated_at_utc      timestamptz,
    updated_by_user_id  integer
);
create unique index if not exists ux_categories_name_lower on categories (lower(name));
create index if not exists ix_categories_parent on categories (parent_category_id);

create table if not exists products (
    id                  integer generated by default as identity primary key,
    sku                 text not null,
    name                text not null,
    description         text not null default '',
    category_id         integer references categories (id) on delete set null,
    unit_price          numeric(18,2) not null default 0,
    cost_price          numeric(18,2) not null default 0,
    unit_of_measure     text not null default 'each',
    quantity_on_hand    numeric(18,3) not null default 0,
    reorder_level       numeric(18,3) not null default 0,
    is_active           boolean not null default true,
    created_at_utc      timestamptz not null default now(),
    created_by_user_id  integer,
    updated_at_utc      timestamptz,
    updated_by_user_id  integer
);
create unique index if not exists ux_products_sku_lower on products (lower(sku));
create index if not exists ix_products_category on products (category_id);
create index if not exists ix_products_active on products (is_active);

create table if not exists suppliers (
    id                  integer generated by default as identity primary key,
    name                text not null,
    contact_name        text not null default '',
    email               text not null default '',
    phone               text not null default '',
    address             text not null default '',
    is_active           boolean not null default true,
    created_at_utc      timestamptz not null default now(),
    created_by_user_id  integer,
    updated_at_utc      timestamptz,
    updated_by_user_id  integer
);

create table if not exists customers (
    id                  integer generated by default as identity primary key,
    code                text not null default '',
    name                text not null,
    contact_name        text not null default '',
    email               text not null default '',
    phone               text not null default '',
    billing_address     text not null default '',
    notes               text not null default '',
    is_active           boolean not null default true,
    created_at_utc      timestamptz not null default now(),
    created_by_user_id  integer,
    updated_at_utc      timestamptz,
    updated_by_user_id  integer
);
create index if not exists ix_customers_code_lower on customers (lower(code));

-- ---------------------------------------------------------------------------
-- 3. Transactions & stock
-- ---------------------------------------------------------------------------

-- type:   1=Sale  2=Purchase  3=AdjustmentIn  4=AdjustmentOut
-- status: 0=Draft 1=Confirmed 2=Cancelled
create table if not exists transactions (
    id                  integer generated by default as identity primary key,
    transaction_number  text    not null,
    type                integer not null,
    status              integer not null default 0,
    transaction_date    timestamptz not null,
    customer_id         integer references customers (id) on delete restrict,
    supplier_id         integer references suppliers (id) on delete restrict,
    subtotal            numeric(18,2) not null default 0,
    tax_total           numeric(18,2) not null default 0,
    total               numeric(18,2) not null default 0,
    notes               text not null default '',
    confirmed_at_utc    timestamptz,
    cancelled_at_utc    timestamptz,
    created_at_utc      timestamptz not null default now(),
    created_by_user_id  integer,
    updated_at_utc      timestamptz,
    updated_by_user_id  integer
);
create index if not exists ix_transactions_number on transactions (transaction_number);
create index if not exists ix_transactions_type_date on transactions (type, transaction_date);
create index if not exists ix_transactions_status on transactions (status);

create table if not exists transaction_lines (
    id              integer generated by default as identity primary key,
    transaction_id  integer not null references transactions (id) on delete cascade,
    product_id      integer not null references products (id)     on delete restrict,
    description     text not null default '',
    quantity        numeric(18,3) not null,
    unit_price      numeric(18,2) not null,
    tax_rate        numeric(9,4)  not null default 0,
    line_subtotal   numeric(18,2) not null default 0,
    line_tax        numeric(18,2) not null default 0,
    line_total      numeric(18,2) not null default 0
);
create index if not exists ix_transaction_lines_transaction on transaction_lines (transaction_id);
create index if not exists ix_transaction_lines_product on transaction_lines (product_id);

-- direction: 1=In 2=Out
-- reason:    1=Sale 2=Purchase 3=Adjustment 4=CancellationReversal 5=OpeningBalance
create table if not exists stock_movements (
    id                   integer generated by default as identity primary key,
    product_id           integer not null references products (id) on delete restrict,
    transaction_line_id  integer references transaction_lines (id) on delete set null,
    direction            integer not null,
    reason               integer not null,
    quantity             numeric(18,3) not null,
    quantity_after       numeric(18,3) not null,
    note                 text not null default '',
    moved_at_utc         timestamptz not null,
    user_id              integer
);
create index if not exists ix_stock_movements_product_date on stock_movements (product_id, moved_at_utc);
create index if not exists ix_stock_movements_line on stock_movements (transaction_line_id);

-- ---------------------------------------------------------------------------
-- 4. Cross-cutting
-- ---------------------------------------------------------------------------

-- action: 1=Create 2=Update 3=Delete
create table if not exists audit_entries (
    id            integer generated by default as identity primary key,
    entity_name   text not null,
    entity_id     text not null default '',
    action        integer not null,
    changes_json  jsonb not null default '{}'::jsonb,
    user_id       integer,
    user_name     text not null default '',
    timestamp_utc timestamptz not null
);
create index if not exists ix_audit_entries_timestamp on audit_entries (timestamp_utc desc);
create index if not exists ix_audit_entries_entity on audit_entries (entity_name, entity_id);

-- type:     1=LowStock 2=PendingApproval 3=System
-- severity: 0=Info 1=Warning 2=Critical
create table if not exists notifications (
    id                   integer generated by default as identity primary key,
    type                 integer not null,
    severity             integer not null default 0,
    title                text not null default '',
    message              text not null default '',
    target_user_id       integer,
    related_entity_name  text not null default '',
    related_entity_id    text not null default '',
    dedupe_key           text not null default '',
    is_read              boolean not null default false,
    created_at_utc       timestamptz not null,
    read_at_utc          timestamptz
);
create index if not exists ix_notifications_target_unread on notifications (target_user_id, is_read);
create index if not exists ix_notifications_dedupe on notifications (dedupe_key);

create table if not exists app_settings (
    id     integer generated by default as identity primary key,
    key    text not null,
    value  text not null default ''
);
create unique index if not exists ux_app_settings_key on app_settings (key);

commit;

-- ============================================================================
--  OPTIONAL — seed data
--  The app also seeds this on first start (DataSeeder.SeedBaseline, idempotent),
--  so you can skip this block. Run it if you want the DB populated up front.
-- ============================================================================

begin;

insert into permissions (code, category, description) values
    ('users.view',           'Users',        'View user accounts'),
    ('users.manage',         'Users',        'Create, edit and deactivate users'),
    ('roles.view',           'Roles',        'View roles and permissions'),
    ('roles.manage',         'Roles',        'Create roles and assign permissions'),
    ('products.view',        'Products',     'View products and stock levels'),
    ('products.edit',        'Products',     'Create and edit products'),
    ('products.delete',      'Products',     'Delete products'),
    ('categories.view',      'Categories',   'View categories'),
    ('categories.edit',      'Categories',   'Create and edit categories'),
    ('customers.view',       'Customers',    'View customers'),
    ('customers.edit',       'Customers',    'Create and edit customers'),
    ('suppliers.view',       'Suppliers',    'View suppliers'),
    ('suppliers.edit',       'Suppliers',    'Create and edit suppliers'),
    ('transactions.view',    'Transactions', 'View transactions'),
    ('transactions.create',  'Transactions', 'Create draft transactions'),
    ('transactions.confirm', 'Transactions', 'Confirm transactions and post stock'),
    ('transactions.cancel',  'Transactions', 'Cancel confirmed transactions'),
    ('inventory.view',       'Inventory',    'View stock ledger and valuation'),
    ('inventory.adjust',     'Inventory',    'Make manual stock adjustments'),
    ('reports.view',         'Reports',      'Run and export reports'),
    ('audit.view',           'Audit',        'View the audit trail'),
    ('settings.manage',      'Settings',     'Change application settings')
on conflict (code) do nothing;

insert into roles (name, description, is_system) values
    ('Admin',   'Full access to every module.',            true),
    ('Manager', 'Day-to-day operations and reporting.',     true),
    ('Staff',   'Create transactions and view catalogue.',  true)
on conflict do nothing;

-- Admin: every permission
insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r cross join permissions p
where r.name = 'Admin'
on conflict do nothing;

-- Manager: operations + reporting
insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r join permissions p on p.code = any (array[
    'products.view','products.edit','categories.view','categories.edit',
    'customers.view','customers.edit','suppliers.view','suppliers.edit',
    'transactions.view','transactions.create','transactions.confirm','transactions.cancel',
    'inventory.view','inventory.adjust','reports.view','audit.view'])
where r.name = 'Manager'
on conflict do nothing;

-- Staff: create transactions + view catalogue
insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r join permissions p on p.code = any (array[
    'products.view','categories.view','customers.view','customers.edit',
    'suppliers.view','transactions.view','transactions.create','inventory.view'])
where r.name = 'Staff'
on conflict do nothing;

-- Administrator account.  Password: ChangeMe#2026  (forced change on first sign-in)
insert into users (user_name, email, full_name, password_hash, role_id, is_active, must_change_password, created_at_utc)
select 'admin', 'admin@example.com', 'System Administrator',
       'PBKDF2-SHA256.210000.I33nsNbZudxpx8Yg1sURbw==.JV2Zhsk3uyyeOohNHY9xjU6ocsRXchAKZEffbBU3uQo=',
       r.id, true, true, now()
from roles r
where r.name = 'Admin'
  and not exists (select 1 from users where lower(user_name) = 'admin');

insert into app_settings (key, value) values
    ('company.name',                     'My Business'),
    ('company.currency',                 'USD'),
    ('tax.defaultRatePercent',           '0'),
    ('inventory.lowStockScanEnabled',    'true')
on conflict (key) do nothing;

commit;

-- ============================================================================
--  OPTIONAL — lock down the public API
--  Enable RLS on every table so the anon / PostgREST API cannot read or write.
--  Your app connects with the Postgres role via the pooler connection string,
--  which BYPASSES RLS, so the application keeps working with no policies.
--  Only run this if you never intend to use Supabase's auto REST API here.
-- ============================================================================

-- alter table roles              enable row level security;
-- alter table permissions        enable row level security;
-- alter table role_permissions   enable row level security;
-- alter table users              enable row level security;
-- alter table categories         enable row level security;
-- alter table products           enable row level security;
-- alter table suppliers          enable row level security;
-- alter table customers          enable row level security;
-- alter table transactions       enable row level security;
-- alter table transaction_lines  enable row level security;
-- alter table stock_movements    enable row level security;
-- alter table audit_entries      enable row level security;
-- alter table notifications      enable row level security;
-- alter table app_settings       enable row level security;
