-- ============================================================================
-- General Management System - PostgreSQL / Supabase schema
--
-- SOURCE OF TRUTH. Run this in the Supabase SQL Editor. GMS.Core maps to these
-- tables via GmsDbContext; it never runs EF migrations.
--
-- The CREATE TABLE section below is generated from the EF Core model itself
-- (DbContext.Database.GenerateCreateScript), so table names, column names and
-- types are guaranteed to match what the application actually queries. Do not
-- hand-edit it: change the VB models in GMS.Core/Models and regenerate.
--
-- Every statement is idempotent - safe to re-run against an existing database.
-- ============================================================================
create table if not exists organizations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    code text,
    email text,
    plan text,
    trial_ends_at_utc timestamp with time zone,
    subscription_ends_at_utc timestamp with time zone,
    is_active boolean NOT NULL,
    max_users integer NOT NULL,
    features text,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_organizations" PRIMARY KEY (id)
);


create table if not exists permissions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text,
    description text,
    category text,
    CONSTRAINT "PK_permissions" PRIMARY KEY (id)
);


create table if not exists roles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    description text,
    is_system boolean NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY (id)
);


create table if not exists app_settings (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    key text,
    value text,
    CONSTRAINT "PK_app_settings" PRIMARY KEY (id),
    CONSTRAINT "FK_app_settings_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists audit_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    entity_name text,
    entity_id text,
    action integer NOT NULL,
    changes_json jsonb,
    user_id integer,
    user_name text,
    timestamp_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audit_entries" PRIMARY KEY (id),
    CONSTRAINT "FK_audit_entries_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    name text,
    description text,
    parent_category_id integer,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_categories_categories_parent_category_id" FOREIGN KEY (parent_category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT "FK_categories_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists customers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    code text,
    name text,
    contact_name text,
    email text,
    phone text,
    billing_address text,
    notes text,
    is_active boolean NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_customers" PRIMARY KEY (id),
    CONSTRAINT "FK_customers_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    type integer NOT NULL,
    severity integer NOT NULL,
    title text,
    message text,
    target_user_id integer,
    related_entity_name text,
    related_entity_id text,
    dedupe_key text,
    is_read boolean NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    read_at_utc timestamp with time zone,
    CONSTRAINT "PK_notifications" PRIMARY KEY (id),
    CONSTRAINT "FK_notifications_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists subscriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    plan text,
    plan_name text,
    price_per_month numeric(18,6) NOT NULL,
    auto_renew boolean NOT NULL,
    billing_cycle_start_at_utc timestamp with time zone NOT NULL,
    billing_cycle_end_at_utc timestamp with time zone NOT NULL,
    stripe_subscription_id text,
    payment_status text,
    cancelled_at_utc timestamp with time zone,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_subscriptions" PRIMARY KEY (id),
    CONSTRAINT "FK_subscriptions_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    name text,
    contact_name text,
    email text,
    phone text,
    address text,
    is_active boolean NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_suppliers" PRIMARY KEY (id),
    CONSTRAINT "FK_suppliers_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists role_permissions (
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT "PK_role_permissions" PRIMARY KEY (role_id, permission_id),
    CONSTRAINT "FK_role_permissions_permissions_permission_id" FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE,
    CONSTRAINT "FK_role_permissions_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);


create table if not exists shops (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    name text,
    code text,
    address text,
    phone text,
    is_active boolean NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_shops" PRIMARY KEY (id),
    CONSTRAINT "FK_shops_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_name text,
    email text,
    full_name text,
    password_hash text,
    role_id integer NOT NULL,
    organization_id integer NOT NULL,
    shop_id integer,
    is_active boolean NOT NULL,
    must_change_password boolean NOT NULL,
    last_login_utc timestamp with time zone,
    failed_login_count integer NOT NULL,
    locked_out_until_utc timestamp with time zone,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_users" PRIMARY KEY (id),
    CONSTRAINT "FK_users_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT "FK_users_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_users_shops_shop_id" FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE RESTRICT
);


create table if not exists products (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    sku text,
    name text,
    description text,
    category_id integer,
    unit_price numeric(18,6) NOT NULL,
    cost_price numeric(18,6) NOT NULL,
    unit_of_measure text,
    quantity_on_hand numeric(18,6) NOT NULL,
    reorder_level numeric(18,6) NOT NULL,
    is_active boolean NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_products" PRIMARY KEY (id),
    CONSTRAINT "FK_products_categories_category_id" FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT "FK_products_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);


create table if not exists shop_stocks (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    shop_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity_on_hand numeric(18,6) NOT NULL,
    unit_price numeric(18,6),
    CONSTRAINT "PK_shop_stocks" PRIMARY KEY (id),
    CONSTRAINT "FK_shop_stocks_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT "FK_shop_stocks_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT "FK_shop_stocks_shops_shop_id" FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE
);


create table if not exists transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    transaction_number text,
    type integer NOT NULL,
    status integer NOT NULL,
    transaction_date timestamp with time zone NOT NULL,
    shop_id integer,
    customer_id integer,
    supplier_id integer,
    subtotal numeric(18,6) NOT NULL,
    tax_total numeric(18,6) NOT NULL,
    total numeric(18,6) NOT NULL,
    notes text,
    confirmed_at_utc timestamp with time zone,
    cancelled_at_utc timestamp with time zone,
    created_at_utc timestamp with time zone NOT NULL,
    created_by_user_id integer,
    updated_at_utc timestamp with time zone,
    updated_by_user_id integer,
    CONSTRAINT "PK_transactions" PRIMARY KEY (id),
    CONSTRAINT "FK_transactions_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_transactions_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT "FK_transactions_shops_shop_id" FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE SET NULL,
    CONSTRAINT "FK_transactions_suppliers_supplier_id" FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT
);


create table if not exists transaction_lines (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    transaction_id integer NOT NULL,
    product_id integer NOT NULL,
    description text,
    quantity numeric(18,6) NOT NULL,
    unit_price numeric(18,6) NOT NULL,
    tax_rate numeric(18,6) NOT NULL,
    line_subtotal numeric(18,6) NOT NULL,
    line_tax numeric(18,6) NOT NULL,
    line_total numeric(18,6) NOT NULL,
    CONSTRAINT "PK_transaction_lines" PRIMARY KEY (id),
    CONSTRAINT "FK_transaction_lines_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_transaction_lines_transactions_transaction_id" FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE CASCADE
);


create table if not exists stock_movements (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id integer NOT NULL,
    product_id integer NOT NULL,
    transaction_line_id integer,
    shop_id integer,
    direction integer NOT NULL,
    reason integer NOT NULL,
    quantity numeric(18,6) NOT NULL,
    quantity_after numeric(18,6) NOT NULL,
    note text,
    moved_at_utc timestamp with time zone NOT NULL,
    user_id integer,
    CONSTRAINT "PK_stock_movements" PRIMARY KEY (id),
    CONSTRAINT "FK_stock_movements_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT "FK_stock_movements_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_stock_movements_shops_shop_id" FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE SET NULL,
    CONSTRAINT "FK_stock_movements_transaction_lines_transaction_line_id" FOREIGN KEY (transaction_line_id) REFERENCES transaction_lines (id) ON DELETE SET NULL
);


create index if not exists "IX_app_settings_organization_id" ON app_settings (organization_id);


create index if not exists "IX_audit_entries_organization_id" ON audit_entries (organization_id);


create index if not exists "IX_categories_organization_id" ON categories (organization_id);


create index if not exists "IX_categories_parent_category_id" ON categories (parent_category_id);


create index if not exists "IX_customers_organization_id" ON customers (organization_id);


create index if not exists "IX_notifications_organization_id" ON notifications (organization_id);


create index if not exists "IX_products_category_id" ON products (category_id);


create index if not exists "IX_products_organization_id" ON products (organization_id);


create index if not exists "IX_role_permissions_permission_id" ON role_permissions (permission_id);


create index if not exists "IX_stock_movements_organization_id" ON stock_movements (organization_id);


create index if not exists "IX_stock_movements_product_id" ON stock_movements (product_id);


create index if not exists "IX_stock_movements_transaction_line_id" ON stock_movements (transaction_line_id);


create unique index if not exists "IX_subscriptions_organization_id" ON subscriptions (organization_id);


create index if not exists "IX_suppliers_organization_id" ON suppliers (organization_id);


create index if not exists "IX_transaction_lines_product_id" ON transaction_lines (product_id);


create index if not exists "IX_transaction_lines_transaction_id" ON transaction_lines (transaction_id);


create index if not exists "IX_transactions_customer_id" ON transactions (customer_id);


create index if not exists "IX_transactions_organization_id" ON transactions (organization_id);


create index if not exists "IX_transactions_supplier_id" ON transactions (supplier_id);


create index if not exists "IX_users_organization_id" ON users (organization_id);


create index if not exists "IX_users_role_id" ON users (role_id);


create index if not exists "IX_users_shop_id" ON users (shop_id);


create index if not exists "IX_transactions_shop_id" ON transactions (shop_id);


create index if not exists "IX_stock_movements_shop_id" ON stock_movements (shop_id);


create index if not exists "IX_shops_organization_id" ON shops (organization_id);


create index if not exists "IX_shop_stocks_organization_id" ON shop_stocks (organization_id);


create index if not exists "IX_shop_stocks_product_id" ON shop_stocks (product_id);


create index if not exists "IX_shop_stocks_shop_id" ON shop_stocks (shop_id);



-- ============================================================================
-- Upgrades to tables that already exist.
--
-- CREATE TABLE IF NOT EXISTS above builds a new database correctly but does
-- nothing to one that is already there, so every column added to an existing
-- table after its first release has to be added again here. Each is nullable
-- with no default, which is what makes this safe to run against live data: an
-- existing row keeps NULL, and NULL shop_id means "central pool" - exactly what
-- every row predating shops actually was.
-- ============================================================================
alter table users           add column if not exists shop_id integer;
alter table transactions    add column if not exists shop_id integer;
alter table stock_movements add column if not exists shop_id integer;

-- Per-shop selling price. NULL means "use the catalogue price", which is what
-- every shop was doing before prices could differ by branch.
alter table shop_stocks     add column if not exists unit_price numeric(18,6);

-- Added separately from the columns because ADD CONSTRAINT has no IF NOT EXISTS.
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'FK_users_shops_shop_id') then
        alter table users add constraint "FK_users_shops_shop_id"
            foreign key (shop_id) references shops (id) on delete restrict;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'FK_transactions_shops_shop_id') then
        alter table transactions add constraint "FK_transactions_shops_shop_id"
            foreign key (shop_id) references shops (id) on delete set null;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'FK_stock_movements_shops_shop_id') then
        alter table stock_movements add constraint "FK_stock_movements_shops_shop_id"
            foreign key (shop_id) references shops (id) on delete set null;
    end if;
end $$;


-- ============================================================================
-- Domain indexes and uniqueness rules.
--
-- Hand-maintained: EF only emits indexes for foreign keys, so the business
-- rules below have to live here.
--
-- IMPORTANT: every uniqueness rule on a tenant-scoped table is keyed on
-- (organization_id, ...). A global unique index here would stop a second
-- organization from ever having its own "admin" user, its own "General"
-- category, or its own copy of a settings key - which is exactly what
-- DataSeeder.SeedBaseline(organizationId) creates for each new tenant.
-- roles and permissions are deliberately global: they are system-wide.
-- ============================================================================

-- Global (not tenant-scoped).
create unique index if not exists ux_roles_name_lower       on roles (lower(name));
create unique index if not exists ux_permissions_code       on permissions (code);

-- Tenant-scoped uniqueness.
create unique index if not exists ux_users_org_user_name    on users (organization_id, lower(user_name));
create unique index if not exists ux_categories_org_name    on categories (organization_id, lower(name));
create unique index if not exists ux_products_org_sku       on products (organization_id, lower(sku));
create unique index if not exists ux_app_settings_org_key   on app_settings (organization_id, key);
create unique index if not exists ux_organizations_code     on organizations (lower(code));
create unique index if not exists ux_shops_org_code         on shops (organization_id, lower(code));

-- One balance row per product per shop. InventoryService creates a row the first
-- time stock reaches a shop and updates it thereafter; two rows for the same pair
-- would split a balance in half and make every availability check wrong.
create unique index if not exists ux_shop_stocks_shop_product on shop_stocks (shop_id, product_id);

-- Lookup indexes for common queries.
create index if not exists ix_customers_org_code            on customers (organization_id, lower(code));
create index if not exists ix_products_active               on products (organization_id, is_active);
create index if not exists ix_transactions_number           on transactions (transaction_number);
create index if not exists ix_transactions_type_date        on transactions (organization_id, type, transaction_date);
create index if not exists ix_transactions_status           on transactions (organization_id, status);
create index if not exists ix_stock_movements_product_date  on stock_movements (product_id, moved_at_utc);
-- The ledger filtered to one shop, newest first. EF's own IX_stock_movements_shop_id
-- above only covers the filter; this covers the sort as well.
create index if not exists ix_stock_movements_shop_product  on stock_movements (shop_id, product_id, moved_at_utc);
create index if not exists ix_transactions_shop_date        on transactions (organization_id, shop_id, transaction_date);
create index if not exists ix_audit_entries_timestamp       on audit_entries (organization_id, timestamp_utc desc);
create index if not exists ix_audit_entries_entity          on audit_entries (entity_name, entity_id);
create index if not exists ix_notifications_target_unread   on notifications (target_user_id, is_read);
create index if not exists ix_notifications_dedupe          on notifications (dedupe_key);

-- ============================================================================
-- Offline sync for the desktop client (same as migrations/2026-09-30-offline-sync.sql).
-- sync_id names a row across the server and every desktop copy; sync_version is
-- stamped on each insert/update so a desktop can fetch what changed since it last
-- looked; sync_tombstones records deletions for the same purpose.
-- ============================================================================
create sequence if not exists gms_sync_version_seq;

create table if not exists sync_tombstones (
    id bigint generated by default as identity primary key,
    table_name text not null,
    row_id integer not null,
    sync_id uuid not null,
    -- NULL for global tables (roles, permissions), which every desktop receives.
    organization_id integer,
    sync_version bigint not null default nextval('gms_sync_version_seq'),
    deleted_at_utc timestamp with time zone not null default now()
);
create index if not exists ix_sync_tombstones_org_version on sync_tombstones (organization_id, sync_version);

-- Not for the Supabase data API. The application connects as the table owner,
-- which row level security does not restrict.
alter table sync_tombstones enable row level security;

create or replace function gms_stamp_sync_version() returns trigger
language plpgsql as $$
begin
    new.sync_version := nextval('gms_sync_version_seq');
    return new;
end
$$;

create or replace function gms_record_tombstone() returns trigger
language plpgsql as $$
declare
    org integer;
begin
    if tg_table_name = 'organizations' then
        org := old.id;
    elsif tg_table_name = 'transaction_lines' then
        -- Lines have no organization_id of their own. When the whole transaction is
        -- being deleted the parent may already be gone; NULL then, which a desktop
        -- matches by sync_id, so the tombstone still lands.
        select t.organization_id into org from transactions t where t.id = old.transaction_id;
    else
        org := (to_jsonb(old) ->> 'organization_id')::integer;
    end if;

    insert into sync_tombstones (table_name, row_id, sync_id, organization_id)
    values (tg_table_name, old.id, old.sync_id, org);
    return old;
end
$$;

do $$
declare
    t text;
begin
    foreach t in array array[
        'organizations', 'subscriptions', 'roles', 'permissions', 'users', 'shops',
        'shop_stocks', 'categories', 'products', 'suppliers', 'customers',
        'transactions', 'transaction_lines', 'stock_movements', 'audit_entries',
        'notifications', 'app_settings'
    ] loop
        execute format('alter table %I add column if not exists sync_id uuid not null default gen_random_uuid()', t);
        execute format('alter table %I add column if not exists sync_version bigint not null default 0', t);
        execute format('create unique index if not exists %I on %I (sync_id)', 'ux_' || t || '_sync_id', t);
        execute format('create index if not exists %I on %I (sync_version)', 'ix_' || t || '_sync_version', t);

        execute format('drop trigger if exists gms_sync_version on %I', t);
        execute format('create trigger gms_sync_version before insert or update on %I '
                       'for each row execute function gms_stamp_sync_version()', t);
        execute format('drop trigger if exists gms_sync_tombstone on %I', t);
        execute format('create trigger gms_sync_tombstone after delete on %I '
                       'for each row execute function gms_record_tombstone()', t);
    end loop;
end
$$;
